---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: checkout
  name: checkout
spec:
  replicas: 1
  selector:
    matchLabels:
      app: checkout
  template:
    metadata:
      labels:
        app: checkout
    spec:
      containers:
      - image: dineshba/dobby:latest
        imagePullPolicy: Always
        name: checkout
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: checkout
  name: checkout
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 4444
  selector:
    app: checkout
  type: ClusterIP
