---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: currency
  name: currency
spec:
  replicas: 1
  selector:
    matchLabels:
      app: currency
  template:
    metadata:
      labels:
        app: currency
    spec:
      containers:
      - image: dineshba/dobby:latest
        imagePullPolicy: Always
        name: currency
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: currency
  name: currency
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 4444
  selector:
    app: currency
  type: ClusterIP
