---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: email
  name: email
spec:
  replicas: 1
  selector:
    matchLabels:
      app: email
  template:
    metadata:
      labels:
        app: email
    spec:
      containers:
      - image: dineshba/dobby:latest
        imagePullPolicy: Always
        name: email
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: email
  name: email
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 4444
  selector:
    app: email
  type: ClusterIP
